name : deploy

on :
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  id-token: write
  contents: read
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name : checking Repository 
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
           role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
           aws-access-key-id : ${{AKIAQRYS3OZNJY3EJ5YR}}
           aws-secret-access-key: ${{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 }}
           aws-region: us-east-2



  



       

      
    
