name : deploy

on :
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name : checking Repository 
        uses: actions/checkout@v2
      - name : configure AWS
        run: |
          echo "[default]
          aws_access_key_id = ${{ AKIASGQ34QLRLL7JXDDJ }}
          aws_secret_access_key = ${{ 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 }}" > ~/.aws/credentials

      - name :  Deploy cloudformation stack 
        run: |
          aws cloudformation create-stack --stack-name stackSfn \
          --template-body file://template.yaml \
          --region us-east-1  # Replace with your desired AWS region

  



       

      
    
