name : deploy

on :
  push:
    branches:
      - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name : checking Repository 
        uses: actions/checkout@v2
      - name : configure AWS
        uses : aws-actions/configure-aws-credentials@v2
        with : 
          aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name :  Deploy cloudformation stack 
        run : aws cloudformation create-stack --stack-name stack_sfn \ 
            --template-body file://Template.yaml \
            --region us-east-1

      
    
